// <auto-generated />
using System;
using Climbbergs.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Climbbergs.infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Climbbergs.Core.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Climbing jackets and outerwear",
                            Name = "Jackets",
                            Slug = "jackets"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Climbing pants and shorts",
                            Name = "Pants",
                            Slug = "pants"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Climbing and approach shoes",
                            Name = "Shoes",
                            Slug = "shoes"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Chalk bags, gloves, and more",
                            Name = "Accessories",
                            Slug = "accessories"
                        });
                });

            modelBuilder.Entity("Climbbergs.Core.Entities.DesignGrip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Angle")
                        .HasColumnType("integer");

                    b.Property<decimal>("Depth")
                        .HasColumnType("numeric");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<int>("GripTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("HangboardDesignId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Height")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PositionX")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PositionY")
                        .HasColumnType("numeric");

                    b.Property<int>("Rotation")
                        .HasColumnType("integer");

                    b.Property<decimal>("Width")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("GripTypeId");

                    b.HasIndex("HangboardDesignId");

                    b.ToTable("DesignGrips");
                });

            modelBuilder.Entity("Climbbergs.Core.Entities.GripType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HasAngle")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasDepth")
                        .HasColumnType("boolean");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("MaxDepth")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MinDepth")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GripTypes");
                });

            modelBuilder.Entity("Climbbergs.Core.Entities.HangboardBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("numeric");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Height")
                        .HasColumnType("numeric");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Width")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("HangboardBases");
                });

            modelBuilder.Entity("Climbbergs.Core.Entities.HangboardDesign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConfigurationJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("text");

                    b.Property<string>("ContactName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HangboardBaseId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsOrderPlaced")
                        .HasColumnType("boolean");

                    b.Property<string>("SessionId")
                        .HasColumnType("text");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("HangboardBaseId");

                    b.ToTable("HangboardDesigns");
                });

            modelBuilder.Entity("Climbbergs.Core.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SKU")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 2, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Waterproof climbing jacket for all conditions",
                            Name = "Alpine Pro Jacket",
                            Price = 299.99m,
                            SKU = "JAC-001",
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 2, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Flexible climbing pants with reinforced knees",
                            Name = "Boulder Pants",
                            Price = 129.99m,
                            SKU = "PNT-001",
                            StockQuantity = 75
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 2, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-performance climbing shoes",
                            Name = "Grip Master Shoes",
                            Price = 189.99m,
                            SKU = "SHO-001",
                            StockQuantity = 30
                        });
                });

            modelBuilder.Entity("Climbbergs.Core.Entities.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AltText")
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("Climbbergs.Core.Entities.ProductInterest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ClickedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("ReferrerUrl")
                        .HasColumnType("text");

                    b.Property<string>("SessionId")
                        .HasColumnType("text");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductInterests");
                });

            modelBuilder.Entity("Climbbergs.Core.Entities.Category", b =>
                {
                    b.HasOne("Climbbergs.Core.Entities.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("Climbbergs.Core.Entities.DesignGrip", b =>
                {
                    b.HasOne("Climbbergs.Core.Entities.GripType", "GripType")
                        .WithMany("DesignGrips")
                        .HasForeignKey("GripTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Climbbergs.Core.Entities.HangboardDesign", "HangboardDesign")
                        .WithMany("Grips")
                        .HasForeignKey("HangboardDesignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GripType");

                    b.Navigation("HangboardDesign");
                });

            modelBuilder.Entity("Climbbergs.Core.Entities.HangboardDesign", b =>
                {
                    b.HasOne("Climbbergs.Core.Entities.HangboardBase", "HangboardBase")
                        .WithMany("Designs")
                        .HasForeignKey("HangboardBaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HangboardBase");
                });

            modelBuilder.Entity("Climbbergs.Core.Entities.Product", b =>
                {
                    b.HasOne("Climbbergs.Core.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Climbbergs.Core.Entities.ProductImage", b =>
                {
                    b.HasOne("Climbbergs.Core.Entities.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Climbbergs.Core.Entities.ProductInterest", b =>
                {
                    b.HasOne("Climbbergs.Core.Entities.Product", "Product")
                        .WithMany("Interests")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Climbbergs.Core.Entities.Category", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("Climbbergs.Core.Entities.GripType", b =>
                {
                    b.Navigation("DesignGrips");
                });

            modelBuilder.Entity("Climbbergs.Core.Entities.HangboardBase", b =>
                {
                    b.Navigation("Designs");
                });

            modelBuilder.Entity("Climbbergs.Core.Entities.HangboardDesign", b =>
                {
                    b.Navigation("Grips");
                });

            modelBuilder.Entity("Climbbergs.Core.Entities.Product", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Interests");
                });
#pragma warning restore 612, 618
        }
    }
}
